### PR TITLE
finer control on action|raw_action filespec

### PR DESCRIPTION
**Pull request by ibhagwan**
This helps avoid bugs when sending output lines from `rg` which contain special chars, for example if your rg output matches a line with say \`text\`, and since the entire line (`{+}`) is sent to `action_helper.sh` the action might fail as it tries to execute what's inside the back-ticks, I couldn't solve it consistently  with `vim.fn.shellescape` and I find this solution better as it gives you more flexibility combined with sending `--delimiter` to `fzf`.

### CODE REVIEW

**Comment by vijaymarupudi** [comment]
* For the first commit, could you provide a minimal example of the bug?
* The second commit makes this plugin way too dependent on a Unix environment, and I don't think it's necessary? You can use `sh -c` in the preview command and that should work I think.

**Comment by ibhagwan** [comment]
Another edge case fix in the last commit, turns out `fish` shell doesn't support back ticks which bugs out when doing more complex commands such as "bat \<args\> `raw_action`", the last commit makes sure our `termopen` opens using `/bin/sh`.

This enables me to extract the filename from the fzf entries without relying on `fzf`'s `--delimiter` and placeholders (e.g. `{+}`)  but running an action instead.

**Comment by vijaymarupudi** [comment]
I suspect there is a more cleaner fix to this, some of the users of this plugin use `fish`, and therefore this will be a breaking change. Does `sh -c` work?

**Comment by ibhagwan** [comment]
>     * For the first commit, could you provide a minimal example of the bug?
> 
>     * The second commit makes this plugin way too dependent on a Unix environment, and I don't think it's necessary? You can use `sh -c` in the preview command and that should work I think.

`sh -c` didn't work for me, if you use my latest version you can reproduce this bug using any `rg` function (`grep` or `live_grep`) on lines that contain back-ticks, the lines with the back ticks will be sent fully to the `nvim-fzf` action and break the command.

**Comment by ibhagwan** [comment]
> I suspect there is a more cleaner fix to this, some of the users of this plugin use `fish`, and therefore this will be a breaking change. Does `sh -c` work?

Perhaps, even so I don't see any harm by adding a fully backward compatible option to send a different fzf placeholder?

**Comment by ibhagwan** [comment]
These two commits fixes [`fzf-lua` issue #24](https://github.com/ibhagwan/fzf-lua/issues/24), follow the link for more info.

**Comment by ibhagwan** [comment]
> The second commit makes this plugin way too dependent on a Unix environment, and I don't think it's necessary? You can use `sh -c` in the preview command and that should work I think.

Let me try and fix this with `sh -c`, will keep you posted.

**Comment by zeertzjq** [comment]
Maybe an option can be added to specify environment variables?

**Comment by vijaymarupudi** [comment]
Ah, so the problem is that the current users might rely on fish being the shell for `fzf`, not `sh`, and therefore changing this will be backwards incompatible.

It fixes the bug in that issue, because that user does not rely on this, but it will break the workflow of other users.  `sh -c` should work, with proper shell escaping. 

As for the second issue, quoting from the [fzf man page](https://www.mankier.com/1/fzf).

> A placeholder expression starting with + flag will be replaced to the space-separated list of the selected lines (or the current line if no selection was made) individually quoted.

So quotation shouldn't be an issue, and all other arguments are escaped properly. Here's a minimal example that shows that there is no problem in how stuff is escaped.

```lua
local fzf = require("fzf")
local fzf_action = require("fzf.actions").action

coroutine.wrap(function ()
  local action = fzf_action(function (items)
    print(items[1])
    return items[1]
  end)
  local result = fzf.fzf({"`item`"}, "--preview=" .. action)
  pp(result)
end)()
```

**Comment by vijaymarupudi** [comment]
I have had a similar issue in the past for `nvim-fzf-commands`, here's the commit that fixed it: https://github.com/vijaymarupudi/nvim-fzf-commands/commit/c6188c8618ca6b579af37cbc242414e1016bcd45

Here's the link to the issue: https://github.com/vijaymarupudi/nvim-fzf-commands/issues/4

**Comment by vijaymarupudi** [comment]
Regarding UNIX dependence, yes, that part is currently UNIX dependent, but it's not user facing, and can be easily fixed once someone with a Windows machine volunteers to add support.

**Comment by ibhagwan** [comment]
Ok, `sh -c` before the preview does solve the fish shell back-tick issue, I am still unable to find a solution for the backticks, not that I'm using it a bit differently, my preview command is `bat <args> <nvim-fzf-action-to-extract-filename-without-icons>`.

Perhaps we can at least keep the first commit, I don't see any harm in having this extra bit of flexibility to provide the fzf placeholder?

**Comment by vijaymarupudi** [comment]
I am open to accepting the first commit, if it is necessary! I'm currently not sure if it is, so I want to investigate more to fully understand it. Can you point me to the spot in fzf-lua where you use the new option? I suspect this is an escaping bug more than an `nvim-fzf `bug.

**Comment by ibhagwan** [comment]
Ok, here's a reproducible minimal function that resembles more to what I'm doing inside `fzf-lua` (basically replace `echo` with `bat` and have the action extract the filename without icons):

```lua
M.test = function()
  local fzf = require("fzf")
  local fzf_action = require("fzf.actions").raw_action

  coroutine.wrap(function ()
    local action = fzf_action(function (items)
      print(items[1])
      return items[1]
    end)
    local action = string.format('sh -c "echo `%s`"', action)
    local cli_args = string.format("--preview=%s", vim.fn.shellescape(action))
    local result = fzf.fzf({"item1", "`item2`"}, cli_args)
    print(result)
  end)()
end
```

And the result when trying to preview `item2`:
screenshot-1628043191

**Comment by ibhagwan** [comment]
FYI, I removed the 2nd commit since we solved the 2nd issue with `sh -c`.

**Comment by vijaymarupudi** [comment]
Wow, this is pretty complicated, props for doing this. 

I can confirm that I can replicate it, and have been looking at it, it's a difficult one to solve. Will respond soon.

**Comment by ibhagwan** [comment]
> Wow, this is pretty complicated, props for doing this.
> 
> I can confirm that I can replicate it, and have been looking at it, it's a difficult one to solve. Will respond soon.

Yes, I'm taking your plugin to the extreme lol

In my defense, I'm not just making it complex for no reason, before that I was actually stripping the icons within `fzf` and using the placeholder for the file path. However, I had other issues [such as this one](https://github.com/ibhagwan/fzf-lua/issues/24).

Some functions can be provided with a `cwd` to shorten the filenames and appear as if this is your cwd using relative paths, but that created an issue with lsp functions such as `references` and `definitions` where some references will be outside of your `cwd` or a similar issue can happen with supplying `cwd` to `oldfiles` some files will be inside your `cwd` and will be shortened but some will stay in absolute paths, that created an issue where I couldn't add the `cwd` globally in the the `fzf` command line so I had to be creative, this gives me full control on path manipulation and also much easier to work with lua string patterns then `fzf` delimiters and placeholders.

Below is a screenshot that would hopefully make this clearer, as you can see in the `oldfiles` output some files (such as `cpp.lua`) is under my `cwd` (my `nvim` config) and is being displayed as a relative path whereas others outside the `cwd` are displayed as absolute paths, this could only be solved with a complex action:

screenshot-1628046198

**Comment by vijaymarupudi** [comment]
Okay, I understand what's happening here. FZF is not designed to handle interpolating the `{+}` in the depths of shell escaping, so it interpolates it in a shallow, single level escaped way. However, in this plugin, we go through multiple layers of escaping. Interpolating a single level escape in a region that is in two nested escapes is a bad idea.

Given that, this problem can be solved using the solution you provided. We need to instead pass the fzf arguments at the top level, at the user's discretion, and then pass these arguments down the rabbit hole to the action.

@ibhagwan, I will most likely merge your commit. Before that, could you write a version of this example that uses the filespec option (and therefore does not have the bug)? That way, this issue will serve as documentation for this rare use case.

And wow, fully using this plugin indeed. I would have never imagined this issue ever occurring!

**Comment by ibhagwan** [comment]
> Given that, this problem can be solved using the solution you provided. We need to instead pass the fzf arguments at the top level, at the user's discretion, and then pass these arguments down the rabbit hole to the action.

Not sure I understand what you mean.

> 
> @ibhagwan, I will most likely merge your commit. Before that, could you write a version of this example that uses the filespec option (and therefore does not have the bug)? That way, this issue will serve as documentation for this rare use case.

A slightly modified example simulating what I use in `fzf-lua` manipulating `rg --vimgrep` output lines:

```lua
M.test = function()
  local fzf = require("fzf")
  local fzf_action = require("fzf.actions").raw_action

  coroutine.wrap(function ()
    local action = fzf_action(function (items)
      print(items[1])
      return items[1]
    end, "{1}")
    local action = string.format('sh -c "echo `%s`"', action)
    local cli_args = string.format("--preview=%s --delimiter=':'",
        vim.fn.shellescape(action))
    _G.dump(cli_args)
    local result = fzf.fzf({
      "file1:line:col: text1",
      "file2:line:col: `text2`",
    }, cli_args)
    print(result)
  end)()
end
```

And the resulting preview:

screenshot-1628053356

Obviously you can play with the placeholder and use as many fields as you'd like **as long as they don't contain the back-ticks**, for example if you can use `{1..3}` to display `file:line:col`

> And wow, fully using this plugin indeed. I would have never imagined this issue ever occurring!

That's why I'm here for lol

**Comment by vijaymarupudi** [comment]
Okay, I think I have more of an understanding of what you are going for. I won't be implementing this fix, because it can easily lead people to errors when they think it's the solution.

If the filename has backticks in this case, then I think there will be the same error. It will work in some cases, but won't in other cases, and I don't want to users to have to think about this confusing behavior.

I think the suggested fix here would be to do everything in the action. My description of the issue in https://github.com/vijaymarupudi/nvim-fzf/pull/18#issuecomment-892355036 is still accurate, the problem is to do with levels of nesting. FZF is not designed for {+} to be in shell escaped quotes. Since you want to use `sh`, you were using multiple level of nested escaping.

If you pull the problem into Lua, then there is no problem because Lua can do the parsing easily. Here's how I would do it.

```lua
local fzf = require("fzf")
local fzf_action = require("fzf.actions").raw_action

coroutine.wrap(function ()
  local action = fzf_action(function (items)
    print(items[1])
    -- i have no processing in this example, so keeping it simple
    local filename = items[1]
    -- alternative with processing:
    -- local filename = vim.split(items[1], ":", true)[1]


    -- use filename here
    return vim.fn.systemlist({"bat", "--color=always", filename}) 

  end)

  local cli_args = string.format("--preview=%s",
      vim.fn.shellescape(action))
  local result = fzf.fzf("ls", cli_args)
  print(result)
end)()
```
Now the problem with this approach is that it's a bit synchronous i.e. if it's an absolutely massive file, neovim will hang. I think the solution to that problem is the creating of an `async_action` API, which I will work on soon. I suspect you will need that API anyways, given that you've used literally every part of this plugin and you'll want the performance.

Really appreciate the time you've spent explaining the problem to me, and I hope the new API will solve any performance problems in the current solution. Given how fast bat is, you probably will not notice it for anything but the largest files, but then the new API will fix that concern too.

**Comment by ibhagwan** [comment]
Interesting solution, I’ll give it a go but in general I’d like to avoid this and stay within the `fzf` ecosystem rather than introducing new complexities and possibly having other issues due to this (it seems simple but using `systemlist` is fundamentally different).

Also, although unlikely I’d like to avoid situations where neovim hangs due to to this, `fzf` has been tested to infinity and never breaks and I’d like to have this option rather than a workaround, I’m already planning to write a separate builtin floating previewer with treesitter support (as in `nvim-bqf`) thus leaving the `bat|cat` to those concerned with performance (treesitter is slow on big files).

You can just add this change without any documentation as a “hidden” feature, it’s merely 3 lines of code that are backward compatible and do nothing when `filespec` is not sent, I see no harm in having greater flexibility with the builtin placeholders, this isn’t a “hack”, most people won’t be confused as I would imagine hardly anyone would reach that depth of the code unless they’re writing a plug-in.

**Comment by vijaymarupudi** [comment]
I understand your concerns and that this change is small, but I think it is not error free, such as when the file itself has backticks, which I consider a pretty major issue (unlikely I acknowledge) that blocks your suggesting fix, and why I consider this issue a pretty important usecase to solve safely.

I want to emphasize that this isn't a departure from plain old `fzf`. The only reason neovim 'hangs' using this current approach is that it will be waiting for bat to finish because `systemlist` is synchronous. It won't be consuming CPU resources or anything like that. But it's easy to solve.

Here's what I plan to do to solve it, I plan to make an async_action API, which allows people to write to a pipe instead of returning values from the action function.

Given that API, the current action API can be implemented in terms of the async_action API, and then there will be no compatibility break, and no performance issues, everything will be seamless and performant.

For the use case when people want to just modify the lines and then run a shell command i.e. your use case, I will write a helper function that makes it pretty easy without having to deal with the complexity of asynchronous code.

Something like this:

```lua
fzf("find .", "--preview=" .. choice_to_shell_cmd_previewer(function(items, ...)
  return "bat --color=always " .. vim.fn.shellescape(vim.split(items, ":")[1])
end))
```

**Comment by ibhagwan** [comment]
> I understand your concerns and that this change is small, but I think it is not error free, such as when the file itself has backticks, which I consider a pretty major issue (unlikely I acknowledge) that blocks your suggesting fix, and why I consider this issue a pretty important usecase to solve safely.

File names with a back tick is a risk I’m willing to take for now, with or without my PR this issue is still possible if someone chooses to do what I did in the sample code, the PR simply gives more flexibility using a builtin fzf mechanism.

> I want to emphasize that this isn't a departure from plain old `fzf`. The only reason neovim 'hangs' using this current approach is that it will be waiting for bat to finish because `systemlist` is synchronous. It won't be consuming CPU resources or anything like that. But it's easy to solve.

I’m aware why this happens, the issue is, from the user’s perspective it hangs, I can’t think of a better reason to stop using a plug-in other than occasional minor (or worse) hangs.

> Here's what I plan to do to solve it, I plan to make an async_action API, which allows people to write to a pipe instead of returning values from the action function.
> 
> Given that API, the current action API can be implemented in terms of the async_action API, and then there will be no compatibility break, and no performance issues, everything will be seamless and performant.
> 
> For the use case when people want to just modify the lines and then run a shell command i.e. your use case, I will write a helper function that makes it pretty easy without having to deal with the complexity of asynchronous code.
> 
> Something like this:
> 
> ```lua
> fzf("find .", "--preview=" .. choice_to_shell_cmd_previewer(function(items, ...)
>   return "bat --color=always " .. vim.fn.shellescape(vim.split(items, ":")[1])
> end))
> ```

Sounds like a great solution!

For now, I’m going to keep my fork until you come up with the solution.

**Comment by vijaymarupudi** [comment]
Just pushed the proposed async_action API and helper, let me know if that works!

**Comment by ibhagwan** [comment]
> Just pushed the proposed async_action API and helper, let me know if that works!

Amazing, I’ll test later today when I’m next to the computer and let you know, hopefully I can migrate the current code to the async helper.

**Comment by ibhagwan** [comment]
FYI, just migrated all the previewers to the new `async_action`, working great.

**Comment by vijaymarupudi** [comment]
Good to hear!

**Pull request closed without merging**
