### PR TITLE
Move floating window creation to lua

### LINKED ISSUE #4: Floating window implementation can be simplified
### Context

When exploring https://github.com/vijaymarupudi/nvim-fzf/issues/3 I realized that it's possible to pass the `--border` option to fzf to draw a border around the fzf frame.

```lua
coroutine.wrap(function()
  local FILES_CMD = 'rg --files --ignore --smart-case --hidden --follow --no-messages --ignore-file ~/.gitignore'
  local DEFAULT_OPTS = table.concat({
    '--inline-info',
    '--multi',
    '--sort',
    '--layout=reverse',
    '--border'
  }, ' ')

  local results = fzf.fzf(FILES_CMD, DEFAULT_OPTS)

  vim.cmd('edit' .. vim.loop.cwd() .. '/' .. results[1])
end)()
```

result:

image

The double border is indicative that we likely can get rid of the complex double window floating implementation we currently utilize, and simply draw a single floating window.

That way users can specify in their fzf options if they want a border or not.

### Simplified implementation in Vimscript:

```vim
" Source: https://github.com/neovim/neovim/issues/9718#issuecomment-546603628
function! nvim_fzf#create_centered_window()
    let width = min([&columns - 4, max([80, &columns - 20])])
    let height = min([&lines - 4, max([20, &lines - 10])])
    let top = ((&lines - height) / 2) - 1
    let left = (&columns - width) / 2
    let opts = {'relative': 'editor', 'row': top, 'col': left, 'width': width, 'height': height, 'style': 'minimal'}

    set winhl=Normal:Normal
    let l:buf = nvim_create_buf(v:false, v:true)
    call nvim_open_win(l:buf, v:true, opts)
    return l:buf
endf
```

result:

image

diff:

image

### Simplified implementation in lua

We could go one step further and move the window implementation to lua making the plugin 100% lua.

```lua
local nvim_fzf = {}

function nvim_fzf.create_centered_window()
  local columns, lines = vim.o.columns, vim.o.lines

  local width = math.min(columns - 4, math.max(80, columns - 20))
  local height = math.min(lines - 4, math.max(20, lines - 10))

  local top = ((lines - height) / 2) -1
  local left = (columns - width) / 2)

  local opts = { relative = 'editor', row = top col = left, width = width, height = height, style = 'minimal' }

  local bufnr = vim.api.nvim_create_buf(false, true)
  vim.api.nvim_openwin(bufnr, true, opts)

  return bufnr
end
```

### PR DESCRIPTION
**Pull request by alexanderjeurissen**
closes #4 

This PR moves the floating window creation to lua.
It also includes some small cleanup and the inclusion of a new `relative floating window` option.

### fzf.fzf (with custom prompt)
Screen Shot 2021-03-09 at 10 15 17 PM

### fzf.fzf_relative (with custom prompt)
image

### CODE REVIEW

**Comment by alexanderjeurissen** [comment]
@vijaymarupudi ready for review

**Comment by vijaymarupudi** [comment]
Great commit! Please review the changes I have made. I allowed the opportunity to provide more customization to the windows, and added a border by default. If you think it's good to go, I'll merge it

**Comment by vijaymarupudi** [comment]
These reason for the configurability is to solve https://github.com/vijaymarupudi/nvim-fzf-commands/issues/1 in one go with this issue

**Comment by alexanderjeurissen** [comment]
@vijaymarupudi lgtm !

**Comment by vijaymarupudi** [comment]
That's a fair reason. The reason I included it is because without it, the default theme causes the window to look like this:

image

Just to be sensitive to defaults, how about this,

```
if colorscheme == default then
  set winhl=Normal:Normal
end
```

**Comment by vijaymarupudi** [comment]
Added some global configuration, which I think should fix all concerns. Let me know if this is good to go.

**Comment by alexanderjeurissen** [comment]
Left a couple of small comments.

RE: higlighting, personally I'm not sure if the way floating windows look in the default theme should be a concern of this plugin.

I'd argue that respecting the `NormalFloat` colorscheme is more in line with expectation than overriding it (regardless if it's ugly). I'd also reckon there are users that override the default colorscheme by having a `colors/default.vim` in which case the current implementation would break.

So my suggestion would be to include a section in the docs with instructions on how to set `NormalFloat` (maybe linking to default nvim docs) or creating a vim help file that explains this. 

But if you're keen on this then go ahead, I'm not going to block the change on this ;-) just sharing my 2c

**Comment by vijaymarupudi** [comment]
Consider me convinced, however I don't want people to have to make their own nvim-fzf wrapper functions just for this bug, so I'll let them use the `window_on_create` option. I want people to have a different background for the floating windows spawned by nvim-fzf if they'd like.

If people really don't like the default behavior, they'll let me know, and then I'll reconsider.

Merging this now.

**Pull request merged**
